#!/usr/bin/python
# -*- coding: utf-8 -*-
frame_goggle_up1 = [{'arm_flex_joint': -0.41,
                     'arm_lift_joint': 0.05,
                     'arm_roll_joint': 3.2,
                     'wrist_flex_joint': -1.4,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.4,
                     'time': 1.0},
                    {'arm_flex_joint': -0.4,
                     'arm_lift_joint': 0.05,
                     'arm_roll_joint': 3.2,
                     'wrist_flex_joint': -1.4,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.4,
                     'time': 1.0}
                    ]

frame_goggle_up2 = [{'arm_flex_joint': -0.55,
                     'arm_lift_joint': 0.2,
                     'arm_roll_joint': 3.2,
                     'wrist_flex_joint': -0.7,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.4,
                     'time': 1.0},
                    {'arm_flex_joint': -0.3,
                     'arm_lift_joint': 0.2,
                     'arm_roll_joint': 2.6,
                     'wrist_flex_joint': -1.0,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.25,
                     'time': 0.3},
                    {'arm_flex_joint': -0.0,
                     'arm_lift_joint': 0.2,
                     'arm_roll_joint': 0.0,
                     'wrist_flex_joint': -1.6,
                     'wrist_roll_joint': 0.0,
                     'head_pan_joint': -0.5,
                     'head_tilt_joint': -0.1,
                     'time': 0.5}
                    ]

frame_goggle_down1 = [{'arm_flex_joint': -0.3,
                     'arm_lift_joint': 0.1,
                     'arm_roll_joint': 3.2,
                     'wrist_flex_joint': -1.0,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.4,
                     'time': 1.0}
                    ]

frame_goggle_down2 = [{'arm_flex_joint': -0.42,
                     'arm_lift_joint': 0.0,
                     'arm_roll_joint': 3.2,
                     'wrist_flex_joint': -1.4,
                     'wrist_roll_joint': 1.6,
                     'head_pan_joint': -0.3,
                     'head_tilt_joint': -0.2,
                     'time': 1.0}]

frame_stick_1 = [{'arm_flex_joint': -0.0,
                     'arm_lift_joint': 0.0,
                     'arm_roll_joint': 0.8,
                     'wrist_flex_joint': -1.55,
                     'wrist_roll_joint': 0.4,
                     'head_pan_joint': -0.0,
                     'head_tilt_joint': -0.0,
                     'time': 1.0},
                    {'arm_flex_joint': -0.4,
                     'arm_lift_joint': 0.05,
                     'arm_roll_joint': 0.8,
                     'wrist_flex_joint': -1.55,
                     'wrist_roll_joint': -0.6,
                     'head_pan_joint': -0.0,
                     'head_tilt_joint': -0.0,
                     'time': 0.8}
                    ]